version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin

    garie-plugin:
        image: garie-sonarqube 
        environment:
            - HOST=influxdb
            - SONARQUBE_API_URL=$SONARQUBE_API_URL
        depends_on:
            - influxdb
        volumes:
            - ./src:/usr/src/garie-plugin/src

    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
