version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin

    garie-plugin:
        build: .
        environment:
            - HOST=influxdb
            - SONARQUBE_API_URL=$SONARQUBE_API_URL
        depends_on:
            - influxdb
        ports:
            - 3000:3000
        volumes:
            - ./src:/usr/src/garie-plugin/src
        command: bash -c "tail -f /dev/null"

    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
